# @format

services:
  levit:
    build: .
    container_name: "levit"
    working_dir: "/workspace"
    tty: true
    runtime: nvidia
    volumes:
      - "/mnt/SSDb/coco2017:/dataB/coco2017"
      - "./:/workspace"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
