services:
  vit:
    build: .
    container_name: "vit"
    volumes:
    - "./:/workspace"
    working_dir: "/workspace"
    tty: true
    environment: 
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
